MSUTeam1/unbanner

README.md

Adds Lawrence Brogan as a collaborator

Begins fixing #1

---

README.md

Attempt 1 to sign the readme to satisfy issue #1

---

README.md

Since a couple changes have been made to `master` since `development` branched off, we need to merge those changes back in.

Merge master into development

---

build.gradle
src/main/java/unbanner/Student.java
src/main/java/unbanner/StudentController.java
src/main/main.iml
src/main/resources/templates/student.html
src/test/java/unbanner/ApplicationTest.java

Added a way to delete students from the database. I changed both the StudentController and the student.html view. I have created a simple form that submits a DELETE request to the controller which in turn deletes that student ID from the database.

Implemented DELETE, UPDATE in Student controller and view

---

.travis.yml
build.gradle
config/checkstyle/checkstyle.xml

Fixes #4 
- .travis.yml
- Force travis to only build against `master` and `development`
- build.gradle
- Add checkstyle plugin
- config/checkstyle/checkstyle.xml
- Copy default Google style
- Remove failing checks

Add checkstyle

---

src/test/java/unbanner/ApplicationTest.java
src/test/java/unbanner/StudentTest.java

Partially addresses #20, #47, #50 
- src/test/java/unbanner/ApplicationTest.java
- Remove test framework prologue
- Add comment to note need for integration tests
- src/test/java/unbanner/StudentTest.java
- Add unit tests for each Student method

Add unit tests for Student class

---

README.md

this is how to do CRUD ops on courses

user docs for courses

---

src/main/java/unbanner/Course.java
src/main/java/unbanner/CourseController.java
src/main/resources/templates/create_course.html
src/main/resources/templates/index.html

made a template to make a new course, needs work still.

create course routes added to controller

---

src/main/java/unbanner/Application.java
src/main/java/unbanner/Course.java
src/main/java/unbanner/Student.java
src/main/resources/templates/student.html
src/test/java/unbanner/CourseTest.java

I have Implemented what is essentially a Many-to-Many relationship between Students and Courses with this pull request. We should be able to build out the rest of the relationships we need for other classes (Courses, Professors, etc...).
I updated the student.html template to display all classes a student is in.
I updated CourseTest.java to comply with CheckStyle
I updated Student.java to add a List<Course> attribute and annotate it as a DBRef
I updated Course.java to add a List<Student> attribute and annotate it as a DBRef
I updated the Application.java to demonstrate updating the course attribute for students.

Spring Data MongoDB

---

src/main/java/unbanner/Application.java
src/main/java/unbanner/Course.java
src/main/java/unbanner/CourseRepository.java
src/main/java/unbanner/Student.java
src/main/resources/templates/course.html
src/main/resources/templates/courses.html
src/main/resources/templates/header.html
src/main/resources/templates/index.html
src/main/resources/templates/students.html
src/test/java/unbanner/CourseControllerTest.java

Finally figured out how to fix the issue with circular references. This is a step in the right direction however there are issues in this pull request still. For instance if you delete a course object it does not right now delete the reference to the course object inside of the student object. This needs to be figured out along with other as of yet unforeseen issues.

DBRefs Lazy Loading, example of how to implement

---

src/main/java/unbanner/Application.java
src/main/main.iml
src/main/resources/templates/course.html
src/main/resources/templates/courses.html
src/main/resources/templates/create_course.html
src/main/resources/templates/create_student.html
src/main/resources/templates/header.html
src/main/resources/templates/index.html
src/main/resources/templates/layout.html
src/main/resources/templates/student.html
src/main/resources/templates/students.html

updated unbanner app to use a hierarchical-style layout. Using thymeleaf-layout-dialect to do this and had to update all exsisting templates.

Site Layout and Navigation

---

src/main/java/unbanner/Application.java
src/main/java/unbanner/Globals.java
src/main/resources/application
src/main/resources/application.properties

Added Global variables via bean

Global Variables

---

build.gradle
src/main/java/unbanner/Application.java
src/main/java/unbanner/Course.java
src/main/java/unbanner/CourseRepository.java
src/main/java/unbanner/Globals.java
src/main/java/unbanner/Section.java
src/main/java/unbanner/SectionController.java
src/main/java/unbanner/SectionRepository.java
src/main/java/unbanner/Student.java
src/main/java/unbanner/StudentController.java
src/main/java/unbanner/Weekday.java
src/main/main.iml
src/main/resources/templates/course.html
src/main/resources/templates/courses.html
src/main/resources/templates/create_course.html
src/main/resources/templates/create_student.html
src/main/resources/templates/header.html
src/main/resources/templates/layout.html
src/main/resources/templates/section.html
src/main/resources/templates/student.html
src/main/resources/templates/students.html
src/test/java/unbanner/CourseControllerTest.java
src/test/java/unbanner/StudentTest.java

Fixed all checkstyle warning with the exception of javadoc warnings - those I ignored.
- Refactored the Student.java class to use Lombok getter and setters.
- Students no longer have Courses but instead have sections, and those sections have courses.
- Changed CourseTest.java to be more of a unit test - removed all mockMvc stuff it belongs in the httpRequestTest
- Changed the delete method in the student controller - now it find all sections containing the student to be deleted, removes the student from those sections, saves the section to repository, then deletes the student from the student repository.
- Updated the overall look of the site by rewriting pretty much every view so that they use bootstrap elements.

Bootstrap, Lombok, Deleting DBRefs

---

.coveralls.yml
.travis.yml
README.md
build.gradle
lombok.config

there is a cool plugin that I want to try and set up
https://coveralls.io/

attempting to setup coveralls plugin

---

src/main/java/unbanner/BuildingController.java
src/main/resources/templates/building.html
src/main/resources/templates/create_room.html
src/main/resources/templates/room.html
src/test/java/unbanner/BuildingControllerTest.java
src/test/java/unbanner/BuildingTest.java
src/test/java/unbanner/HttpBuildingRequestTest.java
src/test/java/unbanner/RoomTest.java

-Creating a Room within a building is now possible.
-Updating a Building now works
-Updating a Room now works.
-Missing tests :(
New file:
create_room.html
I had trouble with creating a room, so I did a small work around, but it's still solid and could be developed upon later.
-Checkstyle adjustments too

Finalizing Building (second try)

---

src/main/java/unbanner/Course.java
src/test/java/unbanner/CourseTest.java
src/test/java/unbanner/WeekdayTest.java

Minor stuff just trying to bring code coverage up some...

wrote a new test, fixed a couple of old tests

---

README.md
src/test/java/unbanner/HttpCourseRequestTest.java

wrote new test that should bring up coverage for the CourseController Class

added HttpCourseRequestTest

---

src/main/java/unbanner/BuildingController.java
src/test/java/unbanner/BuildingTest.java
src/test/java/unbanner/CourseTest.java
src/test/java/unbanner/HttpBuildingRequestTest.java
src/test/java/unbanner/RoomTest.java
src/test/java/unbanner/WeekdayTest.java

Code coverage for all the Building and Room stuff is now complete. Tests could be better, but it gets pretty confusing and difficult at this point, and I can't figure out how to perfect it.
HTTPBuildingRequestTest has been updated.

Tests for buliding

---

msuteam1-unbanner.iml
msuteam1-unbanner.ipr
msuteam1-unbanner.iws
src/main/java/unbanner/Section.java
src/main/java/unbanner/SectionController.java
src/main/java/unbanner/SectionRepository.java
src/test/java/unbanner/SectionControllerTest.java
src/test/java/unbanner/SectionTest.java

This now has 100% code coverage on SectionController

100% code coverage on sectioncontroller

---

gradle/wrapper/gradle-wrapper.properties
src/main/java/unbanner/Application.java
src/main/java/unbanner/Professor.java
src/main/java/unbanner/ProfessorController.java
src/main/java/unbanner/ProfessorRepository.java
src/main/java/unbanner/Section.java
src/main/java/unbanner/SectionRepository.java
src/main/resources/templates/create_professor.html
src/main/resources/templates/header.html
src/main/resources/templates/index.html
src/main/resources/templates/professor.html
src/main/resources/templates/professors.html

Class, HTML and controllers, implemented with basic setup.

Professor Class

---

src/test/java/unbanner/ProfessorControllerTest.java
src/test/java/unbanner/ProfessorTest.java

Used the Student Controller Test as a template, hopefully this looks good.

Professor Controller Tests

---

src/main/java/unbanner/Application.java
src/main/java/unbanner/NineHundred.java
src/main/java/unbanner/NineHundredRepository.java
src/main/java/unbanner/NineHundredService.java
src/main/java/unbanner/NineHundredServiceImpl.java
src/main/java/unbanner/Student.java
src/main/java/unbanner/StudentController.java
src/main/resources/templates/create_student.html
src/main/resources/templates/student.html
src/test/java/unbanner/HttpRequestTest.java
src/test/java/unbanner/StudentTest.java

Implements a custom way to auto generate 900 numbers for students through the use of a Spring Service.

900 numbers

---

gradle/wrapper/gradle-wrapper.properties
src/main/java/unbanner/Application.java
src/main/java/unbanner/CourseController.java
src/main/java/unbanner/Section.java
src/main/java/unbanner/SectionRepository.java
src/main/java/unbanner/Semester.java
src/main/java/unbanner/SemesterController.java
src/main/java/unbanner/SemesterRepository.java
src/main/resources/templates/index.html
src/main/resources/templates/semester.html
src/main/resources/templates/semesters.html
src/test/java/unbanner/SemesterTest.java

Okay, this is a little buggy and a lot late but I suppose it's time to pass the torch.
I believe the plan was for us to get this merged even though it only kinda works such that chris and I can debug it this sprint.

Semester and Semester byproducts

---

src/main/java/unbanner/Section.java
src/test/java/unbanner/SectionTest.java

Before, for test example, we test conflict between these three:
T, TH: 12 - 14
M, W: 13 - 15
F: 12 - 14
M, W: 10 - 11
This should not result in conflict.
Before this fix, it results in conflict.
Now with fix, each day has own list of times. Conflicts arise only in a list of times for same day.

Fixed time conflict problem

---

src/main/java/unbanner/Course.java

Fixed a Null Pointer Exception that was caused because the sections attribute was not initialized.

Fixed error when creating new sections for a new course

---

src/main/java/unbanner/Application.java
src/main/java/unbanner/BuildingController.java
src/main/java/unbanner/RoomRepository.java
src/main/java/unbanner/Section.java
src/main/java/unbanner/SectionRepository.java
src/main/java/unbanner/Semester.java
src/main/java/unbanner/SemesterController.java
src/main/resources/templates/building.html
src/main/resources/templates/buildings.html
src/main/resources/templates/course.html
src/main/resources/templates/create_semester.html
src/main/resources/templates/header.html
src/main/resources/templates/room.html
src/main/resources/templates/semester.html
src/test/java/unbanner/BuildingControllerTest.java

-The delete button for a building or room updates all reference.
-Semester stuff works. Nearly all semester files were changed, functional changes (it now works) + checkstyle changes. 
-Course.html is a bit more informative
-Added semester objects to Application.java and loaded them into their repo.
-Section.java has checkstyle changes. I shouldn't have made changed any functionality.
--------------->No new Semester tests (must be done).

Semester pages are working

---

src/main/java/unbanner/Application.java
src/main/java/unbanner/TestDataService.java
src/main/java/unbanner/TestDataServiceImpl.java

moved all of the code that had to do with initializing test data out of Application.java and into a service instead.

Refactored Application.java 

---

src/main/java/unbanner/Building.java
src/main/java/unbanner/BuildingController.java
src/main/java/unbanner/Course.java
src/main/java/unbanner/Room.java
src/main/java/unbanner/RoomService.java
src/main/java/unbanner/RoomServiceImpl.java
src/main/java/unbanner/TestDataServiceImpl.java
src/main/resources/templates/building.html
src/main/resources/templates/create_room.html
src/main/resources/templates/section.html
src/test/java/unbanner/HttpBuildingRequestTest.java

Verifies that no two rooms have the same name.
Added a Semester data (it got lost in last PR somehow)

Verifies that no two rooms have the same name

---

src/main/java/unbanner/CourseController.java
src/main/java/unbanner/ProfessorRepository.java
src/main/java/unbanner/SectionController.java
src/main/java/unbanner/TestDataServiceImpl.java
src/main/main.iml
src/main/resources/templates/course.html
src/main/resources/templates/create_section.html
src/main/resources/templates/professor.html
src/test/java/unbanner/ProfessorControllerTest.java

Professors can be added to sections and can be seen on the section view

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/unbanner/CourseController.java
src/main/java/unbanner/IndexController.java
src/main/java/unbanner/MessageSecurityWebApplicationInitializer.java
src/main/java/unbanner/MessageWebApplicationInitializer.java
src/main/java/unbanner/RootConfiguration.java
src/main/java/unbanner/SecurityConfig.java
src/main/main.iml
src/main/resources/templates/header.html
src/main/resources/templates/index.html
src/main/resources/templates/student.html
src/test/java/unbanner/HttpBuildingRequestTest.java
src/test/java/unbanner/HttpCourseRequestTest.java
src/test/java/unbanner/HttpRequestTest.java

Just added the required dependancies to the build.gradle so that we can begin implementing spring security. While I was messing with stuff I found that one of the dependancies previously listed was not actually doing anything so I removed it (spring-boot-starter-data-rest).
Also I added the school name from Globals to the index page.

Beginning of Spring Security Implementation

---

src/main/java/unbanner/IndexController.java
src/main/java/unbanner/SecurityConfig.java
src/main/main.iml
src/main/resources/templates/login.html

Set up a custom login page, which redirects to the index after successful login

custom login page

---

src/main/java/unbanner/Application.java
src/main/java/unbanner/Building.java
src/main/java/unbanner/Room.java
src/main/java/unbanner/Section.java
src/main/java/unbanner/SectionController.java
src/main/resources/templates/login.html
src/main/resources/templates/room.html
src/main/resources/templates/section.html
src/test/java/unbanner/BuildingTest.java
src/test/java/unbanner/SectionControllerTest.java

-Can't assign a section to a room if another section is occupying it.
-The sections in a room will be updated correctly now.
-Fixed the issue where "/course/{id}" would crash.
-For convenience, I pre-loaded "user" and "password" into the login fields.

Updating a section works as expected.

---

src/main/java/unbanner/Professor.java
src/main/java/unbanner/ProfessorController.java
src/test/java/unbanner/HttpBuildingRequestTest.java
src/test/java/unbanner/HttpCourseRequestTest.java
src/test/java/unbanner/HttpProfessorRequestTest.java
src/test/java/unbanner/HttpRequestTest.java

Trying to bring coverage up some. I learned a bit about how to write tests, so I refactored some of the integration tests with spring security in mind. Specifically the `@WithMockUser` annotations on all the tests allow for easy testing. 
Also wrote new tests for some of the routes in the professor controller.

Refactored integration tests, some new tests

---

src/main/java/unbanner/CourseController.java
src/main/java/unbanner/ProfessorController.java

fixed professor view now it lists sections

professor view lists sections

---

README.md
build.gradle
src/main/java/unbanner/Building.java
src/main/java/unbanner/BuildingController.java
src/main/java/unbanner/CourseController.java
src/main/java/unbanner/IndexController.java
src/main/java/unbanner/Professor.java
src/main/java/unbanner/ProfessorController.java
src/main/java/unbanner/Room.java
src/main/java/unbanner/RoomServiceImpl.java
src/main/java/unbanner/Section.java
src/main/java/unbanner/SectionController.java
src/main/java/unbanner/SectionService.java
src/main/java/unbanner/SectionServiceImpl.java
src/main/java/unbanner/SemesterRepository.java
src/main/java/unbanner/Student.java
src/main/java/unbanner/StudentController.java
src/main/java/unbanner/TestDataServiceImpl.java
src/main/resources/templates/course.html
src/main/resources/templates/create_section.html
src/main/resources/templates/login.html
src/main/resources/templates/section.html
src/main/resources/templates/semester.html
src/main/resources/templates/student.html
src/test/java/unbanner/SectionControllerTest.java

created a section service, there are a still a lot of methods to move over there from the section class. Update section works, and correctly updates all references as well.

update section finished

---

.travis.yml
src/main/java/unbanner/CourseController.java
src/main/java/unbanner/ProfessorController.java
src/main/java/unbanner/Room.java
src/main/java/unbanner/Section.java
src/main/java/unbanner/SectionController.java
src/main/java/unbanner/SectionServiceImpl.java
src/main/java/unbanner/Semester.java
src/main/java/unbanner/SemesterController.java
src/main/java/unbanner/TestDataServiceImpl.java
src/main/resources/templates/building.html
src/main/resources/templates/course.html
src/main/resources/templates/create_section.html
src/main/resources/templates/create_student.html
src/main/resources/templates/professor.html
src/main/resources/templates/room.html
src/main/resources/templates/section.html
src/main/resources/templates/semester.html
src/main/resources/templates/student.html
src/test/java/unbanner/ApplicationTest.java
src/test/java/unbanner/HttpCourseRequestTest.java

Finished merging Chris's development branch into the noTestData branch I have been working on, there were around 10 merge conflicts that I resolved. Please let me know if you disagree with or question anything, thanks.

Merged Chris's work into the branch I have been working on

---

src/main/java/unbanner/BuildingController.java
src/main/java/unbanner/ProfessorController.java
src/main/java/unbanner/Room.java
src/main/java/unbanner/Section.java
src/main/java/unbanner/SectionController.java
src/main/java/unbanner/SectionServiceImpl.java
src/main/java/unbanner/SemesterController.java
src/main/resources/templates/building.html
src/main/resources/templates/buildings.html
src/main/resources/templates/course.html
src/main/resources/templates/courses.html
src/main/resources/templates/create_section.html
src/main/resources/templates/professor.html
src/main/resources/templates/professors.html
src/main/resources/templates/section.html
src/main/resources/templates/semesters.html
src/main/resources/templates/student.html
src/test/java/unbanner/HttpCourseRequestTest.java
src/test/java/unbanner/HttpProfessorRequestTest.java
src/test/java/unbanner/HttpSectionRequestTest.java
src/test/java/unbanner/SectionControllerTest.java

Reverted the push that was made last night, and saw that building needed a getter/setter in the Room class or else it came up null in thyme leaf. made an attempt at a section http integration test but did not get far

reverted a commit, couple other small fixes
